[package]
name = "command"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
komodo_client.workspace = true
#
svi.workspace = true
#
tokio.workspace = true
tokio-util.workspace = true
shlex.workspace = true
libc.workspace = true
